apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-habitat
  name: hello-habitat
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080 
  selector:
    app: hello-habitat
  type: LoadBalancer
